### ISSUE TITLE
replicate work

### ISSUE THREAD

**Issue by ShaoZhenLiu** [fengshikun/SliDe#1]
This is a very impressive and meaningful work!

However, when I replicate your work under `md17A` dataset. It seems like there are some necessary files missed: 

> "aspirin.npy","benzene2017.npy","ethanol.npy","malonaldehyde.npy","naphthalene.npy","salicylic.npy","toluene.npy","uracil.npy"

Which was provided at here:

https://github.com/fengshikun/SliDe/blob/8364c45673fe3230099a960a760652103102152b/torchmdnet/datasets/md17.py#L136-L145

And was used as below:

https://github.com/fengshikun/SliDe/blob/8364c45673fe3230099a960a760652103102152b/torchmdnet/datasets/md17.py#L186-L188

https://github.com/fengshikun/SliDe/blob/8364c45673fe3230099a960a760652103102152b/torchmdnet/datasets/md17.py#L200-L201

If we don't have those files, we can't use the `md17A` dataset, which is in your config file:

https://github.com/fengshikun/SliDe/blob/8364c45673fe3230099a960a760652103102152b/examples/ET-MD17_FT-angle_f2d.yaml#L9

I have no idea where to get those files, could you help me please?

**Comment by fengshikun** [comment]
Thanks for your attention to our work, this files can be downloaded from: https://1drv.ms/f/c/805267d3bb408a28/EjAUfk0XRgFBmsJSdgtssFwBv8qP8epVDvLBnHhTgyCP2g?e=HBD1me
